### ISSUE TITLE
Escape mentions, hashtags or URL

### ISSUE THREAD

**Issue by fontanon** [andalugeeks/andaluh-www#13]
The `andaluh-js` v1.1.6 package provides with that functionality, as well as escaping the roman numbers as well.

https://www.npmjs.com/package/@andalugeeks/andaluh

**Comment by andalugeek** [comment]
This was already done. Check [evidence](https://drive.google.com/file/d/1vrQ9Mhp3x7Gp1haAtqPNjuGGq7LMEtH5/view?usp=sharing) snapshot
