### ISSUE TITLE
Warn the user that the copy button is not operational when the service is not available

### ISSUE THREAD

**Issue by AnaPraRod** [andalugeeks/andaluh-www#18]
Regarding the "Copy" functionality proposed in https://github.com/andalugeeks/andaluh-www/issues/8, when the service to which it connects is down or unavailable (in this case https://s.andaluh.es/yourls-api.php?signature=d387956c6c&action=shorturl&url=https%3A%2F%2Fandaluh.es%2Ftranscriptor%2F%23%3Ftext%3DEsto%20es%20un%20ejemplo), the button does not work and the user is not aware of it. . 
A possible solution would be to check the status of the service before showing or not the button (or show it disabled with tooltip "Unavailable at this moment" or something like that). 
Another option would be that once you use the functionality and the service gives error, a message is shown on the screen to the user, also of the type "Not available at this moment".

**Comment by fontanon** [comment]
Hi @AnaPraRod 

Very valid point. This is something we should add.
